spring:
  application:
    name: bankhub
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    dev.thiagooliveira.bankhub: DEBUG
    liquibase: DEBUG