spring:
  application:
    name: bankhub-api
  datasource:
    url: jdbc:postgresql://localhost:5432/bankhub
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    dev.thiagooliveira.bankhub: DEBUG
    liquibase: DEBUG