spring:
  docker:
    compose:
      enabled: true
      file: compose-local.yaml
  #datasource:
  #  url: jdbc:postgresql://localhost:5432/bankhub
  #  username: admin
  #  password: admin
  #  driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.web: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    dev.thiagooliveira.bankhub: DEBUG
    liquibase: DEBUG

app:
  seed:
    enabled: true