spring:
  application:
    name: bankhub-api
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:h2:mem:bankhubdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none
server:
  error:
    path: /error
logging:
  level:
    ROOT: WARN
    dev.thiagooliveira.bankhub: INFO
app:
  seed:
    enabled: true
    users:
      - email: john@test.app
        name: John
        password: test
      - email: mary@test.app
        name: Mary
        password: test
    banks:
      - name: ActivoBank
        accounts:
          - name: ActivoBank
            balance: 1000.00
            currency: EUR
    categories:
      - name: Salary John
        type: CREDIT
      - name: Salary Mary
        type: CREDIT
      - name: Apartment Rental
        type: DEBIT
      - name: Electricity Bill
        type: DEBIT
      - name: Water Bill
        type: DEBIT
      - name: Food
        type: DEBIT
      - name: Leisure
        type: DEBIT