spring:
  application:
    name: bankhub-api
  docker:
    compose:
      enabled: false
  datasource:
    url:
    username:
    password:
    driver-class-name:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: none
app:
  seed:
    enabled: false